some-proofs-only-work-without-autoTriggers.dfy(19,11): Info: Selected triggers: {x in a} [Related location] (some-proofs-only-work-without-autoTriggers.dfy(19,36)).
some-proofs-only-work-without-autoTriggers.dfy(20,11): Info: Selected triggers: {x in a[..|a|]} [Related location] (some-proofs-only-work-without-autoTriggers.dfy(20,43)).
some-proofs-only-work-without-autoTriggers.dfy(27,11): Info: Selected triggers: {x in a} [Related location] (some-proofs-only-work-without-autoTriggers.dfy(27,36)).
some-proofs-only-work-without-autoTriggers.dfy(28,11): Info: Selected triggers: {a[i]} [Related location] (some-proofs-only-work-without-autoTriggers.dfy(28,44)).
some-proofs-only-work-without-autoTriggers.dfy(31,11): Info: Selected triggers: {x in a[..3]} [Related location] (some-proofs-only-work-without-autoTriggers.dfy(31,39)).
some-proofs-only-work-without-autoTriggers.dfy(33,11): Info: Selected triggers: {x in a[..2]} [Related location] (some-proofs-only-work-without-autoTriggers.dfy(33,39)).
some-proofs-only-work-without-autoTriggers.dfy(20,11): Error: assertion violation
some-proofs-only-work-without-autoTriggers.dfy(28,11): Error: assertion violation
some-proofs-only-work-without-autoTriggers.dfy(33,11): Error: assertion violation

Dafny program verifier finished with 0 verified, 3 errors
